package bt.db.store.anot;

import java.lang.annotation.ElementType;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;

/**
 * Marks the annotated field so that it wont be persisted.
 * 
 * This is needed if the identity field of that class is an identity always generated by the database, which means that
 * the column of it can't be updated.
 * 
 * @author &#8904
 */
@Retention(RetentionPolicy.RUNTIME)
@Target(ElementType.FIELD)
public @interface NoPersist
{

}
